parameters:
#    cti_forecast.example.class: CTI\ForecastBundle\Example

services:
#    cti_forecast.example:
#        class: %cti_forecast.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
